//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employees.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp
    {
        public int Id { get; set; }
        public int RoleNameId { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Patronymic { get; set; }
        public string Email { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public int SeriaOfPassport { get; set; }
        public int NumberOfPassport { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public System.DateTime LastEnter { get; set; }
        public Nullable<int> EnterTypeId { get; set; }
        public int GenderId { get; set; }
    
        public virtual Enter Enter { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Role Role { get; set; }
    }
}
